# Generated by Django 6.0.4 on 2026-05-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service', models.CharField(choices=[('whatsapp_bot', 'WhatsApp Bot Development'), ('automation', 'Business Automation'), ('website', 'Website Template / Development'), ('mobile_app', 'Mobile App Development'), ('other', 'Other / Multiple Services')], default='other', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Query',
                'verbose_name_plural': 'Contact Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('platform', models.CharField(choices=[('both', 'iOS & Android'), ('ios', 'iOS Only'), ('android', 'Android Only')], default='both', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('emoji', models.CharField(default='📱', max_length=10)),
                ('gradient', models.CharField(default='linear-gradient(135deg,#0a1a35,#0d2558)', max_length=200)),
                ('tech_stack', models.CharField(default='React Native', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('business', 'Business'), ('ecommerce', 'E-Commerce'), ('portfolio', 'Portfolio'), ('restaurant', 'Restaurant'), ('realestate', 'Real Estate'), ('saas', 'SaaS / Tech')], max_length=40)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('emoji', models.CharField(default='🌐', max_length=10)),
                ('gradient', models.CharField(default='linear-gradient(135deg,#0a2a20,#0d3d2b)', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
